version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - mv target/*.jar 02-todo-rest-api-h2-aws-code-pipeline-0.0.1-SNAPSHOT.jar
artifacts:
   files:
    - target/02-todo-rest-api-h2-aws-code-pipeline-0.0.1-SNAPSHOT.jar
 